api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Buildpack for Python"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.10"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.25.4"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.24.5"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.7.12"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.10"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.25.4"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.7.14"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.8"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.8.9"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.10"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.25.4"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.6.18"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.5.12"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.10"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.25.4"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.6.18"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.11.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.6.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.10"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.12.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.10.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.11.0"
