api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Buildpack for Python"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.8.9"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.17.3"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.17.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.6.16"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.8.9"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.17.3"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.5.15"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.8.3"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.7.10"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.8.9"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.17.3"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.6.3"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.15"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.4.17"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.8.9"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.17.3"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.6.3"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.15"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.2"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.8.9"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.10"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.1"
