api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.163"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.111"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.132"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.163"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.132"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.107"
