api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "e7d7f0c99e7a4cf30733d9e388772bd8e500f8c450cc00e1881b4edeefdf2a24"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.141.tar.gz"
    source_sha256 = "0a2a4e9ff4d7344f9b18ce21c62f1596dae08eba288293f563d5e2dc940d3939"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.141/python-runtime-0.0.141.tgz"
    version = "0.0.141"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "6f0a70db41d15149d4e2f279c8b613a87713aa0985e7cc154a7e7ab713389722"
    source = "https://github.com/paketo-community/pip/archive/v0.0.120.tar.gz"
    source_sha256 = "2c1aadf12f6423f64a199c5c854b4cf14a0c014adcb65eed45cc82cae90c82c6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.120/pip-0.0.120.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "aae2428eb4770512782c7904085b3839a57adc6fecc958309fc27c367d2dabd8"
    source = "https://github.com/paketo-community/conda/archive/v0.0.96.tar.gz"
    source_sha256 = "c80dd632d115bb2af665a0576475b93ce307c1b4d56332d1f5930c3dde54c895"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.96/conda-0.0.96.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "7d7dbaef56dbadbfd562410ffdab0095939f5f21fa6e38cf91f2ebe1fe1d8a88"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.101.tar.gz"
    source_sha256 = "74ee98afb4aa7663dcb3ac045247410f14d28555a9d6c454d2db29dbaf02dfe2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.101/pipenv-0.0.101.tgz"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.101"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.120"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.120"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.96"
