api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "75d0b16960d2f3e7013e0e535421a5501ff4a9815ecf77ebdcf4d21bd6e92810"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.127.tar.gz"
    source_sha256 = "692fe1b7c41d0779469f12ecfa384197a97d1ee4e1a6edf4be47dbf565ed8be9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.127/python-runtime-0.0.127.tgz"
    version = "0.0.127"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "74c8a1973f9154e0a62620e5dc02cc4690aadab1a7937625b814c3087e9fb0ac"
    source = "https://github.com/paketo-community/pip/archive/v0.0.115.tar.gz"
    source_sha256 = "d46f24a59314ce5a8ccd88f642d28296bd79259b42e85b3a69b122404e92bdb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.115/pip-0.0.115.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "1d90e1c6cfb7f7017ce05165355af00d85a252658792bdc25ec07670cd586f29"
    source = "https://github.com/paketo-community/conda/archive/v0.0.89.tar.gz"
    source_sha256 = "1e3c7e6a19039abcfe2acb2235c2a9dc3c5ddfa4899b04788c6223c2c759c367"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.89/conda-0.0.89.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "ee8df874a1257d323b8dec8409b68589b2ce7b0dba754fa191f0f967f9d7c073"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.97.tar.gz"
    source_sha256 = "df7f74e030b39b098fef2b95cd6daffaf3a2a1aeb59cea16c069cbd7de3b3760"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.97/pipenv-0.0.97.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.127"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.115"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.89"
