api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "67ed028e2b0570db7c7e8d17f916fa00f43edda795d4cc14566a91591ed6d54e"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.134.tar.gz"
    source_sha256 = "b2b1b6c91d72b60071adef37e2c2b728b72b567040496ea5866fe69ccc50b284"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.134/python-runtime-0.0.134.tgz"
    version = "0.0.134"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "a4009aae26808fcc0ef59cb0410ef796791aa3d20b4e9ba735095fb201552dff"
    source = "https://github.com/paketo-community/pip/archive/v0.0.119.tar.gz"
    source_sha256 = "8a8180de07926d3c9dfed7fd6b2e128c067d99e9f209055535bffae74c807035"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.119/pip-0.0.119.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "d4cd401b6cfa1c8e2a5ed731fcd0212e998b8964059d65c902fef4db44cac2b2"
    source = "https://github.com/paketo-community/conda/archive/v0.0.94.tar.gz"
    source_sha256 = "8d33a73d34d044acbe05360ac84402bdbc5af6436cc6d2d8629ced25f64cb86d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.94/conda-0.0.94.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "7d7dbaef56dbadbfd562410ffdab0095939f5f21fa6e38cf91f2ebe1fe1d8a88"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.101.tar.gz"
    source_sha256 = "74ee98afb4aa7663dcb3ac045247410f14d28555a9d6c454d2db29dbaf02dfe2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.101/pipenv-0.0.101.tgz"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.134"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.101"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.119"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.134"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.119"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.94"
