api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Buildpack for Python"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.14.2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.22.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.21.6"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.6.24"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.19"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.14.2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.22.1"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.6.6"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.19"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.10.4"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.7.14"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.19"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.14.2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.22.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.9.4"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.23"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.4.36"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.14.2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.22.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.9.4"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.23"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.19"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.14.2"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.19"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"
