api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "7a990046f6451c8ae394ec23d74562328481396598a9f246462acd9c0955ccb7"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.133.tar.gz"
    source_sha256 = "99814d6a2b81167d3feb00f34ec652c94980ab323225c0db96224c109524aa1f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.133/python-runtime-0.0.133.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "74c8a1973f9154e0a62620e5dc02cc4690aadab1a7937625b814c3087e9fb0ac"
    source = "https://github.com/paketo-community/pip/archive/v0.0.115.tar.gz"
    source_sha256 = "d46f24a59314ce5a8ccd88f642d28296bd79259b42e85b3a69b122404e92bdb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.115/pip-0.0.115.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "683402388e0c0d159f14026db14f43310bd6a2db0c8d8a5ff460f88e563bce9b"
    source = "https://github.com/paketo-community/conda/archive/v0.0.90.tar.gz"
    source_sha256 = "54f64cbca9e43989b21c5df015d654706c886437f906bdb98f92f41f971d2645"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.90/conda-0.0.90.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "ee8df874a1257d323b8dec8409b68589b2ce7b0dba754fa191f0f967f9d7c073"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.97.tar.gz"
    source_sha256 = "df7f74e030b39b098fef2b95cd6daffaf3a2a1aeb59cea16c069cbd7de3b3760"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.97/pipenv-0.0.97.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.97"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.115"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.115"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.90"
