api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "df0830b91d09281e9b8e3db339e9a359be54a63d6a0503e866280d2395838814"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.128.tar.gz"
    source_sha256 = "76745c2c29b247bf602723691271bcf8d943d99a2c1126d17c3a7e6b004805b8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.128/python-runtime-0.0.128.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "a26daefffcd67d1cf0faeeb975b3f052af7b819595cf794cdd8adaa4169c36ff"
    source = "https://github.com/paketo-community/pip/archive/v0.0.116.tar.gz"
    source_sha256 = "1713f85cb33e308cf4a6073658ce5aa0c972605df225e0c61e6acb160a51eb55"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.116/pip-0.0.116.tgz"
    version = "0.0.116"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "683402388e0c0d159f14026db14f43310bd6a2db0c8d8a5ff460f88e563bce9b"
    source = "https://github.com/paketo-community/conda/archive/v0.0.90.tar.gz"
    source_sha256 = "54f64cbca9e43989b21c5df015d654706c886437f906bdb98f92f41f971d2645"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.90/conda-0.0.90.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "ee8df874a1257d323b8dec8409b68589b2ce7b0dba754fa191f0f967f9d7c073"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.97.tar.gz"
    source_sha256 = "df7f74e030b39b098fef2b95cd6daffaf3a2a1aeb59cea16c069cbd7de3b3760"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.97/pipenv-0.0.97.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.116"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.90"
