api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.164"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.134"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.164"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.134"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.108"
