api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "89c8deb0c58aee3cdc904d24ee1b17a1027e3cd16a6c7ca8da54548925ae40cc"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.136.tar.gz"
    source_sha256 = "db87405a4db3a107afed4d9e4d3921d49d967fbdc257b6ce001df95ec448d9d7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.136/python-runtime-0.0.136.tgz"
    version = "0.0.136"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "a4009aae26808fcc0ef59cb0410ef796791aa3d20b4e9ba735095fb201552dff"
    source = "https://github.com/paketo-community/pip/archive/v0.0.119.tar.gz"
    source_sha256 = "8a8180de07926d3c9dfed7fd6b2e128c067d99e9f209055535bffae74c807035"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.119/pip-0.0.119.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "16bff4dc5df96a4598c5de37a000c3d94fdf8a9151340d3a052ed881461fbb83"
    source = "https://github.com/paketo-community/conda/archive/v0.0.95.tar.gz"
    source_sha256 = "d2682af61ec626b134f56a19243adcd3dff63a555e93171a3388e1f0d1da3fc5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.95/conda-0.0.95.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "6c90a4f1e9538333ae7577b577aa8f8ca5b3f546b1a753e04c38f6bd3ee8745c"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.102.tar.gz"
    source_sha256 = "4152ad1b19cd6e40509cb1169b43d143620091b5b1eb34b269699e3990f2e8cd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.102/pipenv-0.0.102.tgz"
    version = "0.0.102"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.136"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.102"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.119"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.136"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.119"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.95"
