api = "0.6"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Python Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.4"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "0.2.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.2.3"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.4"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.2.1"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.1"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.0.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.4"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.1"
