api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Python Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.14.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.4.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.12.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.14.1"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.5.1"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.12.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.5.1"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.12.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.14.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.3.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.4.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.14.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.3.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.1"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.12.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.3.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.6.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.3.0"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.12.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.3.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.2.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.2.0"
