api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "137aba90c3fe1ea713a7bc5d36060cbedd9c5f543aefb89047053dae19eeff0c"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.120.tar.gz"
    source_sha256 = "27b3262befe0166ad05372077c39a7b2bd88c5d491cfa82729e9629e33686bab"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.120/python-runtime-0.0.120.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "463714ded97379fb0c471a45f41868d3e3676acda4c38617e26d2e36407c741c"
    source = "https://github.com/paketo-community/pip/archive/v0.0.111.tar.gz"
    source_sha256 = "18e02ccf093108007bb3b5335e6f3e1d2760153536a03d8f27379a51f9116dcb"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.111/pip-0.0.111.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "aed49bff39e81ea0c0a4bafba0d6d2e9833ab30b9f3967a5ab6eada08d53a2a6"
    source = "https://github.com/paketo-community/conda/archive/v0.0.88.tar.gz"
    source_sha256 = "09d7970f2db64860ff017a445030d6c814311f229ea911d864635acf0a3f0638"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.88/conda-0.0.88.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "462bfea8972b801f09291b87048a3da269088d6c0ff7d2fc9da656b234193386"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.92.tar.gz"
    source_sha256 = "7ee484c6a2813e3180f1560ebaa05b7f849b71bff18148666343842d352953ed"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.92/pipenv-0.0.92.tgz"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.120"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.111"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.88"
