api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "0c1d287a5fffcb3ec46c9090bdf1acefaff5176efe8f561be1fc624be098d811"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.119.tar.gz"
    source_sha256 = "52c45280893e7fd0e739ded5163d72d49edfb1afe65e34d6746d238047aba6c1"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.119/python-runtime-0.0.119.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "463714ded97379fb0c471a45f41868d3e3676acda4c38617e26d2e36407c741c"
    source = "https://github.com/paketo-community/pip/archive/v0.0.111.tar.gz"
    source_sha256 = "18e02ccf093108007bb3b5335e6f3e1d2760153536a03d8f27379a51f9116dcb"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.111/pip-0.0.111.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "aed49bff39e81ea0c0a4bafba0d6d2e9833ab30b9f3967a5ab6eada08d53a2a6"
    source = "https://github.com/paketo-community/conda/archive/v0.0.88.tar.gz"
    source_sha256 = "09d7970f2db64860ff017a445030d6c814311f229ea911d864635acf0a3f0638"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.88/conda-0.0.88.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "a5fdbbdc8a8102597cd578d169169b13655f3c8db078c601010ac22e31e5455e"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.94.tar.gz"
    source_sha256 = "40a914431b0a5e0f0ff025424cd759a2331342a68d65ca27d907faa31d5b1a97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.94/pipenv-0.0.94.tgz"
    version = "0.0.94"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.94"
    optional = true

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.111"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.88"
