api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Buildpack for Python"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.14"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.26.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.24.9"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.7.16"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.14"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.26.1"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.7.18"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.12"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.8.13"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.14"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.26.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.16.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.6.22"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.5.16"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.14"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.26.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.16.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.6.22"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.12.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.18.14"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.15.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.13.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.12.0"
