api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "df0830b91d09281e9b8e3db339e9a359be54a63d6a0503e866280d2395838814"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.128.tar.gz"
    source_sha256 = "76745c2c29b247bf602723691271bcf8d943d99a2c1126d17c3a7e6b004805b8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.128/python-runtime-0.0.128.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "74c8a1973f9154e0a62620e5dc02cc4690aadab1a7937625b814c3087e9fb0ac"
    source = "https://github.com/paketo-community/pip/archive/v0.0.115.tar.gz"
    source_sha256 = "d46f24a59314ce5a8ccd88f642d28296bd79259b42e85b3a69b122404e92bdb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.115/pip-0.0.115.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "1f82339d105ed87be2e61614ca5cf496cfa864c23e2bb6b17c74ec19d63ad3a1"
    source = "https://github.com/paketo-community/conda/archive/v0.0.92.tar.gz"
    source_sha256 = "7c1009b25a1d6f628f65b0e7dda7c1eea6edf799dee2019fdd131d8ad831d9ed"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.92/conda-0.0.92.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "ee8df874a1257d323b8dec8409b68589b2ce7b0dba754fa191f0f967f9d7c073"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.97.tar.gz"
    source_sha256 = "df7f74e030b39b098fef2b95cd6daffaf3a2a1aeb59cea16c069cbd7de3b3760"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.97/pipenv-0.0.97.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.115"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.92"
