api = "0.2"

[buildpack]
  id = "paketo-community/python"
  name = "Python Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/python-runtime"
    sha256 = "8647fc66e2af7c328daa47a44685929e7a882bd40beea21d7aed8eae581ef9c3"
    source = "https://github.com/paketo-community/python-runtime/archive/v0.0.145.tar.gz"
    source_sha256 = "b67a72b6ae87df41405ebe300163e69bc46b3d9b842264874f8168d2b3d43635"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/python-runtime/releases/download/v0.0.145/python-runtime-0.0.145.tgz"
    version = "0.0.145"

  [[metadata.dependencies]]
    id = "paketo-community/pip"
    sha256 = "6f0a70db41d15149d4e2f279c8b613a87713aa0985e7cc154a7e7ab713389722"
    source = "https://github.com/paketo-community/pip/archive/v0.0.120.tar.gz"
    source_sha256 = "2c1aadf12f6423f64a199c5c854b4cf14a0c014adcb65eed45cc82cae90c82c6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pip/releases/download/v0.0.120/pip-0.0.120.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "paketo-community/conda"
    sha256 = "7267a9751ea6db9dee8c6dc76e23abe9ae7ed5cfbd222e3cd233f163afb488d0"
    source = "https://github.com/paketo-community/conda/archive/v0.0.97.tar.gz"
    source_sha256 = "517f2bf9aef83f78604396adc483093f794ef9fb8b85b2a81a67f79431bc7069"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/conda/releases/download/v0.0.97/conda-0.0.97.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "paketo-community/pipenv"
    sha256 = "cadc63eff5edec39a7614771deabb9e4815bcfb2732dd8daa824b9d3be13f5dd"
    source = "https://github.com/paketo-community/pipenv/archive/v0.0.104.tar.gz"
    source_sha256 = "30f1609b292bb67608acb8ea46d5a12f3d65082092b705af05df2cf0a85edb9e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/pipenv/releases/download/v0.0.104/pipenv-0.0.104.tgz"
    version = "0.0.104"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.145"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.0.104"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.120"

[[order]]

  [[order.group]]
    id = "paketo-community/python-runtime"
    version = "0.0.145"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.0.120"

[[order]]

  [[order.group]]
    id = "paketo-community/conda"
    version = "0.0.97"
