api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Buildpack for Python"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/python/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.13.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.20.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.21.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.6.19"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.13.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.20.1"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.10.0"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "0.7.13"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.13.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.20.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.8.0"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.19"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.4.22"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.13.0"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.20.1"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "0.8.0"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "0.3.19"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.7.0"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.1.1"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "1.13.0"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.8.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.6.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.6.0"
