api = "0.5"

[buildpack]
  id = "paketo-community/python"
  name = "Paketo Python Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.4.1"

  [[order.group]]
    id = "paketo-community/pipenv"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-community/pipenv-install"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"

[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-community/pip"
    version = "0.4.1"

  [[order.group]]
    id = "paketo-community/pip-install"
    version = "0.1.2"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"

[[order]]

  [[order.group]]
    id = "paketo-community/miniconda"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-community/conda-env-update"
    version = "0.2.1"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"

[[order]]

  [[order.group]]
    id = "paketo-community/cpython"
    version = "0.7.0"

  [[order.group]]
    id = "paketo-community/python-start"
    version = "0.6.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.1.1"
